let
    // Step 1: Load data from Azure Data Explorer
    Source = AzureDataExplorer.Contents("https://ade.loganalytics.io/subscriptions/58cb357e-51af-4f62-8982-a8c2b9059362/resourcegroups/rg-eus-desktopmanagement-nerdio-weu-prd/providers/microsoft.operationalinsights/workspaces/nmw-app-law-fwjv4wn75m4qg", "nmw-app-law-fwjv4wn75m4qg", "WVDConnections#(lf)| where TimeGenerated >= ago(30d)#(lf)| where State == ""Connected""#(lf)| where ClientSideIPAddress != ""<>""#(lf)| distinct ClientSideIPAddress", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
    #"Extract First 2 Octets for Reference Purposes" = Table.AddColumn(Source, "Text Before Delimiter", each Text.BeforeDelimiter([ClientSideIPAddress], ".", {1, RelativePosition.FromEnd}), type text),
    #"Renamed Columns" = Table.RenameColumns(#"Extract First 2 Octets for Reference Purposes",{{"Text Before Delimiter", "1st2Octets"}}),
    #"Extract First 3 Octets for Reference Purposes" = Table.AddColumn(#"Renamed Columns", "Text Before Delimiter", each Text.BeforeDelimiter([ClientSideIPAddress], ".", {0, RelativePosition.FromEnd}), type text),
    #"Renamed Columns1" = Table.RenameColumns(#"Extract First 3 Octets for Reference Purposes",{{"Text Before Delimiter", "1st3Octets"}}),
    #"4-fn_ConvertIP4toNumeric on ClientSideIP Address" = Table.AddColumn(#"Renamed Columns1", "ClientSideIPAddress (numeric)", each #"4-fn_ConvertIP4toNumeric"([ClientSideIPAddress])),
    #"4-fn_ConvertIP4toNumeric on 1st2Octets" = Table.AddColumn(#"4-fn_ConvertIP4toNumeric on ClientSideIP Address", "1st2Octets (numeric)", each #"4-fn_ConvertIP4toNumeric"([1st2Octets])),
    #"4-fn_ConvertIP4toNumeric on 1st3Octets" = Table.AddColumn(#"4-fn_ConvertIP4toNumeric on 1st2Octets", "1st3Octets (numeric)", each #"4-fn_ConvertIP4toNumeric"([1st3Octets])),
    #"Removed Duplicates" = Table.Distinct(#"4-fn_ConvertIP4toNumeric on 1st3Octets", {"1st2Octets"}),
    #"Invoked Custom Function" = Table.AddColumn(#"Removed Duplicates", "2-fn_GetIPAddressDetails (API)", each #"2-fn_GetIPAddressDetails (API)"([ClientSideIPAddress])),
    #"Expanded 2-fn_GetIPAddressDetails (API)" = Table.ExpandTableColumn(#"Invoked Custom Function", "2-fn_GetIPAddressDetails (API)", {"city", "country", "countryCode", "isp", "lat", "lon", "org", "regionName", "timezone"}, {"city", "country", "countryCode", "isp", "lat", "lon", "org", "regionName", "timezone"}),
    #"Added Conditional Column" = Table.AddColumn(#"Expanded 2-fn_GetIPAddressDetails (API)", "Country Groupings", each if Text.Contains([timezone], "Europe") then "EMEA" else if Text.Contains([timezone], "Asia") then "APAC" else if Text.Contains([timezone], "America") then "AMRS" else if Text.Contains([timezone], "Australia") then "APAC" else if Text.Contains([timezone], "Africa") then "EMEA" else "Other")
in
    #"Added Conditional Column"
